#!/bin/bash

CPCACHE_COMMENT_LINE="$(grep -n '#\( \)*cpcache' /etc/pacman.d/mirrorlist | cut -f1 -d:)"
CPCACHE_LINE="$((CPCACHE_COMMENT_LINE + 1))"
URL_LINE=$(awk "NR==${CPCACHE_LINE}" /etc/pacman.d/mirrorlist | sed 's/^Server\( \)*=\( \)*//')

py_script="
url = '$URL_LINE'
from urllib.parse import urlparse
result = urlparse(url)
print(url[:len(url) - len(result.path)])
"
CPCACHE_URL=$(python -c "$py_script")

if [ -z "$CPCACHE_URL" ]; then
    >&2 echo "Unable to find cpcache mirror in /etc/pacman.d/mirrorlist"
    >&2 echo "Please ensure that one entry exists with a trailing !cpcache comment."
    exit 1
fi

TMPFILE="$(mktemp)"
HASHFILE="$(mktemp)"
pacman -Qq > "$TMPFILE"
KEY="$(cat /etc/clyde_client/key)"
TIMESTAMP="$(date +%s)"
cat "$TMPFILE" > "$HASHFILE"
echo "$TIMESTAMP" >> "$HASHFILE"
HMAC="$(hmac256 "$KEY" < "$HASHFILE")"
curl --fail -s -S --data-binary @"$TMPFILE" "$CPCACHE_URL/$(hostname)" -H 'Content-Type:text/plain; charset=utf8' -H "Authorization:$HMAC" -H "Timestamp: $TIMESTAMP"
rm "$TMPFILE"
rm "$HASHFILE"
