#!/bin/bash

THEN=0

URL_LINE="$(sed -ne 's/^Server = \(.*\)#\s\+\!cpcache/\1/p' /etc/pacman.d/mirrorlist | head -n1)"
py_script="
url = '$URL_LINE'
from urllib.parse import urlparse
result = urlparse(url)
print(url[:len(url) - len(result.path)])
"
CPCACHE_URL=$(python -c "$py_script")

if [ -z "$CPCACHE_URL" ]; then
    >&2 echo "Unable to find cpcache mirror in /etc/pacman.d/mirrorlist"
    >&2 echo "Please ensure that one entry exists with a trailing !cpcache comment."
    exit 1
fi

set_arch() {
    ARCH=$(sed -ne 's/^Architecture\s\+=\s\+\(.*\)/\1/p' /etc/pacman.conf)
    if [ "$ARCH" = "auto" ]; then
        ARCH="$(uname -m)"
    fi
}

update() {
    pacman -Qq | curl -s -S --data-binary @- "$CPCACHE_URL/$ARCH/$(hostname)" -H 'Content-Type:text/plain; charset=utf8'
}

set_arch
update

while read -r line; do
    if [ "$line" = "db.lck" ]; then
        while pgrep -u root pacman > /dev/null; do
            sleep .1;
        done
        NOW="$(date +%s)"
        DIFF=$((NOW-THEN))
        if [ $DIFF -ge 1 ]; then
            update
        fi
        THEN="$NOW"
    fi
done < <(inotifywait -qm /var/lib/pacman -e DELETE --format %f)
